### ISSUE TITLE
I can't use ADALiOS

### ISSUE THREAD

**Issue by gil-** [microsoftgraph/ios-swift-connect-rest-sample#1]
When I try to compile the project, an error appears in Xcode and stops me from testing anything,
it fails when I use the project in this repo, and with blank projects with cocoapods, I tried with the version 1.2.4 and 1.2.5

<img width="1148" alt="captura de pantalla 2016-04-23 a las 6 52 26 pm" src="https://cloud.githubusercontent.com/assets/6866978/14764643/720bdea0-0985-11e6-8dfa-24f0392501c7.png">

I hope you can help me with this

**Comment by bmitchell287** [comment]
Hi gil, we'll look into this. Thanks for logging.

**Comment by bmitchell287** [comment]
Hi Gil, we noticed that you're not using the sample from this repo. Does the original connect sample work for you?

This section is reserved for issues with this sample only. Perhaps you could field your question to Azure group (ADALiOS) - https://github.com/AzureAD/azure-activedirectory-library-for-objc

Thanks

**Comment by gil-** [comment]
You're right, the screenshot isn't from this project, but it didn't work with the project, so I decided to try it in a new one. The errors are the same for both projects.

Maybe I should try also in the URL you mentioned.

 Thanks

Enviado desde Outlook Mobile

On Mon, Apr 25, 2016 at 12:49 PM -0700, "Brendan Mitchell" notifications@github.com wrote:

Hi Gil, we noticed that you're not using the sample from this repo. Does the original connect sample work for you?

This section is reserved for issues with this sample only. Perhaps you could field your question to Azure group (ADALiOS) - https://github.com/AzureAD/azure-activedirectory-library-for-objc

Thanks

---

**Comment by bmitchell287** [comment]
Sounds good. I tried against 1.2.4 and 1.2.5 and it appeared to work fine in my test environment (didn't get the same ADAL error(s). However, we'll keep looking into it.
