### ISSUE TITLE
App while sigin process fails always

### ISSUE THREAD

**Issue by paresh-navadiya** [microsoftgraph/ios-swift-connect-rest-sample#14]
Operation <DDWebKitOperation: 0x6000000f6980>: container <WebFrame: 0x60000001a6a0> has been modified too many times, aborting

Error appears like Additional Information: Domain: ADAuthenticationErrorDomain ProtocolCode:(null) Details:The operation couldn’t be completed. (ADAuthenticationErrorDomain error 25.). ErrorCode: 25.

Attached is proof of it

![simulator screen shot 11-jul-2017 3 11 15 pm](https://user-images.githubusercontent.com/1125736/28062400-69756684-664b-11e7-8174-cbccfccc9090.png)

**Comment by JohnMAustin78** [comment]
Can you try authentication again with the current version of the sample? We've updated the authentication library and the auth process is different... as is the app registration. It should work for you now.
