### ISSUE TITLE
couldn't login to my account

### ISSUE THREAD

**Issue by saikirannani123** [microsoftgraph/ios-swift-connect-rest-sample#15]
Being new to coding I'm confused where I'm getting wrong to login to the outlook. Here is the message that i got in Log after typing my email address in email field to Login'[MC] System group container for systemgroup.com.apple.configurationprofiles path is /Users/vinu/Library/Developer/CoreSimulator/Devices/52670CB6-2FCC-443E-8063-EC15975A43AA/data/Containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
2017-09-05 18:29:25.997063+0530 O365-iOS-Snippets[2714:94424] [MC] Reading from private effective user settings.
' and here is the message that I got in simulator 'We received a bad request'.

Can you help me with that to login to my account

**Comment by JohnMAustin78** [comment]
It looks like you haven't configured the sample correctly. Did you register your app with the Azure App registration portal? You'll use the client Id that you get back to update the Info.plist file (per readme) to create the correct url.
