### ISSUE TITLE
Unable to open file

### ISSUE THREAD

**Issue by rahyoung** [microsoftgraph/ios-swift-connect-rest-sample#20]
xCode is looking for the following file: "ios-swift-connect-rest-sample/Pods/Target Support Files/Pods-O365-iOS-Microsoft-Graph-Connect-Swift/Pods-O365-iOS-Microsoft-Graph-Connect-Swift.release.xcconfig" but it was not in the cloned project. 

Any suggestions for how to solve this?

**Comment by jasonjoh** [comment]
Did you try cleaning the project?

**Comment by jasonjoh** [comment]
Also, try running pod install from the terminal.

**Comment by rahyoung** [comment]
Thanks pod install worked.
