### ISSUE TITLE
Linker command failed with exit code 1

### ISSUE THREAD

**Issue by simula-r** [microsoftgraph/ios-swift-connect-rest-sample#3]
When I try to build I get this

ld: library not found for -lPods
clang: error: linker command failed with exit code 1 (use -v to see invocation)

note: swift 2.2 | ios 9.2 | xcode 7

**Comment by bmitchell287** [comment]
@JakeSchroeder Hey Jake, could you clone again? Think this might be an issue with a new upgrade of Cocoapods. I checked in a fix recently. Thanks for trying it out.

**Comment by DianeD** [comment]
Hi @JakeSchroeder . Thanks for reporting the issue! Please reopen this if you're still having problems.
