### ISSUE TITLE
Error with code: 3072 Domain

### ISSUE THREAD

**Issue by rajahimanath** [microsoftgraph/ios-swift-connect-rest-sample#6]
i was able to run it in Xcode 8 with swift 3 and was able to run the app and it launched the login screen and after giving credentials. i am getting this error..

Error with code: 3072 Domain: NSCocoaErrorDomain ProtocolCode:(null) Details:The operation was cancelled.. Inner error details: Error Domain=NSCocoaErrorDomain Code=3072 "The operation was cancelled." 

ADALiOS [2016-09-30 16:05:09 - 3F121A33-38BE-4243-81CD-XXXXXXX] ERROR: authorization error. Additional Information: The operation was cancelled.. ErrorCode: 3072.

Can you please point me to the right direction?

**Comment by EshuSuku** [comment]
did your issue resolved now? we are also facing the same issue.

**Comment by jamescro** [comment]
Sorry that it took so long to respond. We haven't been able to reproduce this issue, so I'll close this. Please reopen if this problem persists for you.
