### ISSUE TITLE
How to check token expiration?

### ISSUE THREAD

**Issue by rajahimanath** [microsoftgraph/ios-swift-connect-rest-sample#7]
HI,

I was able to successfully use this api and get the user authenticated. But when I am trying to navigate around my pages i always want to check the validity of the token within the app. Right now I am making the acquire token call which tries to launch the web view and if the session is valid it tries to close the web view by itself. But the user experience is not that great. If there is call i could make which would let me know the current session and token are valid then it would be great. Is there any solution to this.

Also I have been requested to use touchID for my application. Can you please throw any pointers whether we would be able to achieve this via graph api or by using any other api?

Please let me know.

Thank You,
Raja

**Comment by unpluggedk** [comment]
1. For validity of the token, ADAL has acquireTokenSilentWithResource (in 1.2.x) or something similar in 2.x version.

2. For the touch ID, I can't think of a de-facto way, but for the start, there are 2 things to be considered. One is on how to use touch ID, and the other being how to handle the authentication. 

My advise would be to have a mechanism such that 
a. have user authenticate using oauth2 and credentials for initial login
b. have touch id enabled
c. when app is started, check touch id and if success, allow user to use the token in the cache.

**Comment by jamescro** [comment]
Thanks for the feedback. Closing for now. Please reopen if you have other issues you'd like to explore.
