### ISSUE TITLE
401 Status Code returned

### ISSUE THREAD

**Issue by briviere** [microsoftgraph/ios-swift-connect-rest-sample#8]
I'm not sure how if someone can check on the SendMail server side in order to determine what is happening?

2017-01-28 18:20:48.811 O365-iOS-Microsoft-Graph-Connect-Swift[24125:498220] -[ADAuthenticationBroker webAuthenticationDidCompleteWithURL:][379][main] 
response: Optional(<NSHTTPURLResponse: 0x7fb5d070a850> { URL: https://graph.microsoft.com/v1.0/me/microsoft.graph.sendmail } { status code: 401, headers {
    "Cache-Control" = private;
    "Content-Type" = "application/json";
    Date = "Sat, 28 Jan 2017 23:21:27 GMT";
    Duration = "11449.9383";
    Server = "Microsoft-IIS/8.5";
    "Transfer-Encoding" = Identity;
    "X-Powered-By" = "ASP.NET";
    "client-request-id" = "ca06952d-21da-41f0-876d-0aa2c4fd1960";
    "request-id" = "ca06952d-21da-41f0-876d-0aa2c4fd1960";
    "x-ms-ags-diagnostic" = "{\"ServerInfo\":{\"DataCenter\":\"North Central US\",\"Slice\":\"SliceA\",\"ScaleUnit\":\"002\",\"Host\":\"AGSFE_IN_2\",\"ADSiteName\":\"CHI\"}}";
} })
Optional("{\r\n  \"error\": {\r\n    \"code\": \"UnknownError\",\r\n    \"message\": \"\",\r\n    \"innerError\": {\r\n      \"request-id\": \"ca06952d-21da-41f0-876d-0aa2c4fd1960\",\r\n      \"date\": \"2017-01-28T23:21:28\"\r\n    }\r\n  }\r\n}")

**Comment by DianeD** [comment]
Hi @briviere . Sorry for the delayed response. Are you still experiencing this issue?

**Comment by briviere** [comment]
Yes I think I figured it out.  I had to use go back to a older version of xcode.

thanks

brian

**Comment by DianeD** [comment]
Thanks for the feedback @briviere ! We added a note to the readme that calls this out more specifically.
