### ISSUE TITLE
OneDrive Business Sign In doesn't work for some accounts

### ISSUE THREAD

**Issue by salpieiev** [microsoftgraph/ios-swift-connect-rest-sample#9]
I'm unable to sign in to some OneDrive business account. Below you can find the error appears in logs:

ERROR: Error raised: 15. Additional Information: Domain: ADAuthenticationErrorDomain ProtocolCode:access_denied Details:AADSTS65005: The client application has requested access to resource 'https://graph.microsoft.com'. This request has failed because the client has not specified this resource in its requiredResourceAccess list.

**Comment by DianeD** [comment]
Hi @salpeev . Sorry for the delayed response. Are you still experiencing this issue?

**Comment by salpieiev** [comment]
Hi! Yes, this issue still reproducable with some accounts.

**Comment by DianeD** [comment]
**IGNORE: This comment does not apply to native apps**

Is the **Multi-tenanted** property set to Yes for your registered app? If not, can you please set it to Yes and see if it resolves this issue? 

In the [Azure portal](https://portal.azure.com/), open the app registration and choose **Settings > Properties > Multi-tenanted > Yes**. Save your changes and try logging into the app again.

**Comment by salpieiev** [comment]
Sorry, I don't see such option:
<img width="879" alt="1" src="https://cloud.githubusercontent.com/assets/1250605/23508847/2aefca68-ff5c-11e6-8a22-9755feb21274.png">
Is it correct place?

**Comment by DianeD** [comment]
Sorry @ saldeev. I mixed up my app types. To confirm your issue, some work or school accounts (previously called Office 365 accounts) can successfully sign in but some get the error above. Are the users in different organizations?

**Comment by salpieiev** [comment]
Seems like admin accounts can login successfully, but other accounts in the same organization fails to login

**Comment by DianeD** [comment]
Hi @salpeev . I'll see if I can repro. Are these test (dev) tenants? Sometimes test user accounts aren't licensed to access resources.

**Comment by salpieiev** [comment]
Hi @DianeD. I can reproduce this issue in this way:
1. Create admin account (in my case in trial mode)
2. Add some child account to this organization
3. Try to login with child account - login failed.

Also I can reproduce this issue with paid account. So this issue happens in production mode too.

**Comment by DianeD** [comment]
Thanks @salpeev . I'm checking with the team about how we can troubleshoot your account issues.

It seems like a common reason for this error is not specifying "Sign in and read user profile" permission for the app in the [Azure portal](https://portal.azure.com/). Since you can sign in and run the sample with some accounts, it doesn't sound like it's related, but just in case: 

Did you request the Microsoft Graph delegated permissions as described below?

>Configure Permissions for your application - in the Settings menu, choose the Required permissions section, click on Add, then Select an API, and type "Microsoft Graph" in the text box. Then, click on Select Permissions and select:
>- Send mail as a user
>- Sign in and read user profile

**Comment by salpieiev** [comment]
Here're the specified permissions on https://manage.windowsazure.com/
<img width="806" alt="1" src="https://cloud.githubusercontent.com/assets/1250605/24100831/8c512dda-0d7e-11e7-90b2-2b4362ed1132.png">

And permissions on https://portal.azure.com:
<img width="626" alt="2" src="https://cloud.githubusercontent.com/assets/1250605/24100830/8c25cf5a-0d7e-11e7-9e3e-dc77cd9fc3c8.png">

As you can see "Send mail as a user" is specified. But I don't see "Sign in and read user profile" so I'm unable to add it. Also I don't see how can I manage permissions on Azure Portal. All permissions in readonly mode here.

**Comment by DianeD** [comment]
Hi @salpeev . Can you please check your pictures? It looks like they're for a different app. 

Sorry, I'm unable to reproduce your issue. I created a new Office 365 trial tenant and added two users. As long as the "Sign in and read user profile" delegated permission is set for either Windows Azure Active Directory or MicrosoftGraph, I'm able to sign into the app as the admin and the two users.

**Comment by JohnMAustin78** [comment]
No repro.
